name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_cpp_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.6.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: |
          git clone --branch 7.9.0 https://github.com/jtv/libpqxx.git
          cd libpqxx
          cmake -S . -B build -DSKIP_BUILD_TEST=ON
          cmake --build build
          sudo cmake --install build
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: build/PqxxTest
