name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_cpp_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: |
          git clone --branch 7.10.0 https://github.com/jtv/libpqxx.git
          cd libpqxx
          CXXFLAGS=-std=c++17 ./configure
          make
          sudo make install
      - run: cmake -S test -B test/build
      - run: cmake --build test/build
      - run: test/build/pqxx_test

      # test install
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: sudo cmake --install build
