name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ankane/setup-postgres@v1
      with:
        database: pgvector_cpp_test
    - run: |
        sudo apt-get update && sudo apt-get install postgresql-server-dev-14
        git clone --branch v0.2.1 https://github.com/pgvector/pgvector.git
        cd pgvector
        make
        sudo make install
    - run: |
        git clone --branch 7.7.0 https://github.com/jtv/libpqxx.git
        cd libpqxx
        ./configure
        make
        sudo make install
    - run: g++ -std=c++17 -o test/pqxx test/pqxx_test.cpp -lpqxx -lpq
    - run: test/pqxx
